---
name: POE-Component-CPAN-LinksToDocs-No404s-Remember
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: non-blocking wrapper around CPAN::LinksToDocs::No404s::Remember module
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CPAN::LinksToDocs::No404s::Remember: 0.002
  Carp: 1.04
  POE: 0.9999
  POE::Component::NonBlockingWrapper::Base: 0.001
build_requires:
  Test::More: 0
provides:
  POE::Component::CPAN::LinksToDocs::No404s::Remember:
    file: lib/POE/Component/CPAN/LinksToDocs/No404s/Remember.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
